# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0002_auto_20190108_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('column', models.CharField(max_length=20, null=True)),
                ('describe', models.CharField(default='作者很懒，没有写描述', max_length=100, null=True)),
                ('content', models.TimeField()),
                ('img', models.ImageField(null=True, upload_to='article')),
                ('comments', models.CharField(max_length=300, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('g_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
