# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0004_auto_20190109_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=30)),
                ('c_name', models.CharField(max_length=30)),
                ('describe', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'column',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='c',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backweb.Column'),
        ),
    ]
