# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0005_auto_20190110_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='head_portrait',
            field=models.ImageField(null=True, upload_to='user'),
        ),
        migrations.AddField(
            model_name='user',
            name='professional',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wx',
            field=models.ImageField(null=True, upload_to='user'),
        ),
    ]
