# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0006_auto_20190111_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_skills',
            field=models.TextField(null=True),
        ),
    ]
