# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0008_user_user_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='professional',
            field=models.TextField(null=True),
        ),
    ]
