# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0009_auto_20190111_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments',
        ),
    ]
